CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251208204523_InitialCreate') THEN
    CREATE TABLE "Politicians" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "FullName" character varying(100) NOT NULL,
        "Cpf" character varying(50),
        "PoliticalPosition" character varying(50) NOT NULL,
        "Party" character varying(100),
        "State" character varying(2),
        "City" character varying(100),
        "ExternalId" character varying(20),
        "PhotoUrl" character varying(500),
        "IsActive" boolean NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_Politicians" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251208204523_InitialCreate') THEN
    CREATE TABLE "Proposals" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "ExternalId" character varying(20) NOT NULL,
        "Title" character varying(200) NOT NULL,
        "Description" text,
        "Type" character varying(50) NOT NULL,
        "Number" character varying(20),
        "Year" integer NOT NULL,
        "Chamber" character varying(50) NOT NULL,
        "Author" character varying(100),
        "Summary" character varying(500),
        "Status" character varying(50) NOT NULL,
        "ProposalDate" timestamp with time zone,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_Proposals" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251208204523_InitialCreate') THEN
    CREATE TABLE "PoliticianExpenses" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "PoliticianId" integer NOT NULL,
        "Description" character varying(200) NOT NULL,
        "Category" character varying(100) NOT NULL,
        "Amount" numeric(15,2) NOT NULL,
        "Provider" character varying(100),
        "DocumentNumber" character varying(50),
        "ExpenseDate" timestamp with time zone NOT NULL,
        "Month" character varying(50),
        "Year" integer NOT NULL,
        "ExternalId" character varying(20),
        "CreatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_PoliticianExpenses" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_PoliticianExpenses_Politicians_PoliticianId" FOREIGN KEY ("PoliticianId") REFERENCES "Politicians" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251208204523_InitialCreate') THEN
    CREATE TABLE "VotingSessions" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "ExternalId" character varying(50) NOT NULL,
        "ProposalId" integer NOT NULL,
        "Description" character varying(200) NOT NULL,
        "VotingDate" timestamp with time zone NOT NULL,
        "SessionType" character varying(50),
        "TotalVotes" integer NOT NULL,
        "VotesYes" integer NOT NULL,
        "VotesNo" integer NOT NULL,
        "VotesAbstention" integer NOT NULL,
        "VotesAbsent" integer NOT NULL,
        "Result" character varying(20) NOT NULL,
        "Chamber" character varying(50) NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_VotingSessions" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_VotingSessions_Proposals_ProposalId" FOREIGN KEY ("ProposalId") REFERENCES "Proposals" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251208204523_InitialCreate') THEN
    CREATE TABLE "Votes" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "PoliticianId" integer NOT NULL,
        "VotingSessionId" integer NOT NULL,
        "VoteValue" character varying(20) NOT NULL,
        "Justification" character varying(200),
        "CreatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_Votes" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Votes_Politicians_PoliticianId" FOREIGN KEY ("PoliticianId") REFERENCES "Politicians" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_Votes_VotingSessions_VotingSessionId" FOREIGN KEY ("VotingSessionId") REFERENCES "VotingSessions" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251208204523_InitialCreate') THEN
    CREATE INDEX "IX_PoliticianExpenses_ExternalId" ON "PoliticianExpenses" ("ExternalId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251208204523_InitialCreate') THEN
    CREATE INDEX "IX_PoliticianExpenses_PoliticianId" ON "PoliticianExpenses" ("PoliticianId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251208204523_InitialCreate') THEN
    CREATE INDEX "IX_Politicians_Cpf" ON "Politicians" ("Cpf");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251208204523_InitialCreate') THEN
    CREATE INDEX "IX_Politicians_ExternalId" ON "Politicians" ("ExternalId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251208204523_InitialCreate') THEN
    CREATE INDEX "IX_Proposals_ExternalId" ON "Proposals" ("ExternalId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251208204523_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_Votes_PoliticianId_VotingSessionId" ON "Votes" ("PoliticianId", "VotingSessionId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251208204523_InitialCreate') THEN
    CREATE INDEX "IX_Votes_VotingSessionId" ON "Votes" ("VotingSessionId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251208204523_InitialCreate') THEN
    CREATE INDEX "IX_VotingSessions_ExternalId" ON "VotingSessions" ("ExternalId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251208204523_InitialCreate') THEN
    CREATE INDEX "IX_VotingSessions_ProposalId" ON "VotingSessions" ("ProposalId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251208204523_InitialCreate') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20251208204523_InitialCreate', '9.0.5');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251216215546_AddSenatorsDataStructure') THEN
    ALTER TABLE "Politicians" ADD "CurrentLegislaturePublicCode" character varying(20);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251216215546_AddSenatorsDataStructure') THEN
    ALTER TABLE "Politicians" ADD "Email" character varying(100);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251216215546_AddSenatorsDataStructure') THEN
    ALTER TABLE "Politicians" ADD "Gender" character varying(20);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251216215546_AddSenatorsDataStructure') THEN
    ALTER TABLE "Politicians" ADD "IsBoardMember" boolean NOT NULL DEFAULT FALSE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251216215546_AddSenatorsDataStructure') THEN
    ALTER TABLE "Politicians" ADD "IsLeadershipMember" boolean NOT NULL DEFAULT FALSE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251216215546_AddSenatorsDataStructure') THEN
    ALTER TABLE "Politicians" ADD "ParlamentaryName" character varying(100);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251216215546_AddSenatorsDataStructure') THEN
    ALTER TABLE "Politicians" ADD "ParlamentaryPageUrl" character varying(500);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251216215546_AddSenatorsDataStructure') THEN
    ALTER TABLE "Politicians" ADD "PersonalPageUrl" character varying(500);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251216215546_AddSenatorsDataStructure') THEN
    ALTER TABLE "Politicians" ADD "PoliticalBlocId" integer;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251216215546_AddSenatorsDataStructure') THEN
    ALTER TABLE "Politicians" ADD "Treatment" character varying(50);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251216215546_AddSenatorsDataStructure') THEN
    CREATE TABLE "PoliticalBlocs" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Code" integer NOT NULL,
        "Name" character varying(200) NOT NULL,
        "Nickname" character varying(50),
        "CreationDate" date NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_PoliticalBlocs" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251216215546_AddSenatorsDataStructure') THEN
    CREATE TABLE "PoliticianMandates" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "PoliticianId" integer NOT NULL,
        "MandateCode" integer NOT NULL,
        "State" character varying(2) NOT NULL,
        "ParticipationDescription" character varying(100) NOT NULL,
        "TitularPoliticianId" integer,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_PoliticianMandates" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_PoliticianMandates_Politicians_PoliticianId" FOREIGN KEY ("PoliticianId") REFERENCES "Politicians" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_PoliticianMandates_Politicians_TitularPoliticianId" FOREIGN KEY ("TitularPoliticianId") REFERENCES "Politicians" ("Id") ON DELETE SET NULL
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251216215546_AddSenatorsDataStructure') THEN
    CREATE TABLE "PoliticianPhones" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "PoliticianId" integer NOT NULL,
        "PhoneNumber" character varying(20) NOT NULL,
        "PublicationOrder" integer NOT NULL,
        "IsFax" boolean NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_PoliticianPhones" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_PoliticianPhones_Politicians_PoliticianId" FOREIGN KEY ("PoliticianId") REFERENCES "Politicians" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251216215546_AddSenatorsDataStructure') THEN
    CREATE TABLE "Legislatures" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "MandateId" integer NOT NULL,
        "Number" integer NOT NULL,
        "StartDate" date NOT NULL,
        "EndDate" date NOT NULL,
        "LegislatureType" character varying(20) NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_Legislatures" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Legislatures_PoliticianMandates_MandateId" FOREIGN KEY ("MandateId") REFERENCES "PoliticianMandates" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251216215546_AddSenatorsDataStructure') THEN
    CREATE TABLE "MandateExercises" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "MandateId" integer NOT NULL,
        "ExerciseCode" integer NOT NULL,
        "StartDate" date NOT NULL,
        "EndDate" date,
        "LeaveReasonCode" character varying(10),
        "LeaveReasonDescription" character varying(200),
        "ReadingDate" date,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_MandateExercises" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_MandateExercises_PoliticianMandates_MandateId" FOREIGN KEY ("MandateId") REFERENCES "PoliticianMandates" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251216215546_AddSenatorsDataStructure') THEN
    CREATE TABLE "MandateSubstitutes" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "MandateId" integer NOT NULL,
        "SubstitutePoliticianId" integer NOT NULL,
        "ParticipationDescription" character varying(100) NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_MandateSubstitutes" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_MandateSubstitutes_PoliticianMandates_MandateId" FOREIGN KEY ("MandateId") REFERENCES "PoliticianMandates" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_MandateSubstitutes_Politicians_SubstitutePoliticianId" FOREIGN KEY ("SubstitutePoliticianId") REFERENCES "Politicians" ("Id") ON DELETE RESTRICT
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251216215546_AddSenatorsDataStructure') THEN
    CREATE INDEX "IX_Politicians_Email" ON "Politicians" ("Email");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251216215546_AddSenatorsDataStructure') THEN
    CREATE INDEX "IX_Politicians_PoliticalBlocId" ON "Politicians" ("PoliticalBlocId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251216215546_AddSenatorsDataStructure') THEN
    CREATE INDEX "IX_Legislatures_MandateId" ON "Legislatures" ("MandateId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251216215546_AddSenatorsDataStructure') THEN
    CREATE INDEX "IX_MandateExercises_ExerciseCode" ON "MandateExercises" ("ExerciseCode");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251216215546_AddSenatorsDataStructure') THEN
    CREATE INDEX "IX_MandateExercises_MandateId" ON "MandateExercises" ("MandateId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251216215546_AddSenatorsDataStructure') THEN
    CREATE INDEX "IX_MandateSubstitutes_MandateId" ON "MandateSubstitutes" ("MandateId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251216215546_AddSenatorsDataStructure') THEN
    CREATE INDEX "IX_MandateSubstitutes_SubstitutePoliticianId" ON "MandateSubstitutes" ("SubstitutePoliticianId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251216215546_AddSenatorsDataStructure') THEN
    CREATE UNIQUE INDEX "IX_PoliticalBlocs_Code" ON "PoliticalBlocs" ("Code");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251216215546_AddSenatorsDataStructure') THEN
    CREATE INDEX "IX_PoliticianMandates_MandateCode" ON "PoliticianMandates" ("MandateCode");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251216215546_AddSenatorsDataStructure') THEN
    CREATE INDEX "IX_PoliticianMandates_PoliticianId" ON "PoliticianMandates" ("PoliticianId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251216215546_AddSenatorsDataStructure') THEN
    CREATE INDEX "IX_PoliticianMandates_TitularPoliticianId" ON "PoliticianMandates" ("TitularPoliticianId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251216215546_AddSenatorsDataStructure') THEN
    CREATE INDEX "IX_PoliticianPhones_PoliticianId" ON "PoliticianPhones" ("PoliticianId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251216215546_AddSenatorsDataStructure') THEN
    ALTER TABLE "Politicians" ADD CONSTRAINT "FK_Politicians_PoliticalBlocs_PoliticalBlocId" FOREIGN KEY ("PoliticalBlocId") REFERENCES "PoliticalBlocs" ("Id") ON DELETE SET NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20251216215546_AddSenatorsDataStructure') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20251216215546_AddSenatorsDataStructure', '9.0.5');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260324231424_AddFederalDeputyExternalIdLength') THEN
    ALTER TABLE "Politicians" ALTER COLUMN "ExternalId" TYPE character varying(50);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260324231424_AddFederalDeputyExternalIdLength') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260324231424_AddFederalDeputyExternalIdLength', '9.0.5');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260508003837_AddBacklogEntities') THEN
    CREATE TABLE "AssetDeclarations" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "PoliticianId" integer NOT NULL,
        "ElectionYear" integer NOT NULL,
        "AssetType" character varying(100) NOT NULL,
        "DeclaredValue" numeric(15,2) NOT NULL,
        "Description" character varying(500),
        "ExternalId" character varying(50),
        "CreatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_AssetDeclarations" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_AssetDeclarations_Politicians_PoliticianId" FOREIGN KEY ("PoliticianId") REFERENCES "Politicians" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260508003837_AddBacklogEntities') THEN
    CREATE TABLE "CampaignExpenses" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "PoliticianId" integer NOT NULL,
        "ElectionYear" integer NOT NULL,
        "Category" character varying(100) NOT NULL,
        "Amount" numeric(15,2) NOT NULL,
        "Provider" character varying(200),
        "ProviderCnpj" character varying(20),
        "Description" character varying(500),
        "ExternalId" character varying(50),
        "CreatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_CampaignExpenses" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_CampaignExpenses_Politicians_PoliticianId" FOREIGN KEY ("PoliticianId") REFERENCES "Politicians" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260508003837_AddBacklogEntities') THEN
    CREATE TABLE "Committees" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "ExternalId" character varying(50),
        "Name" character varying(200) NOT NULL,
        "Acronym" character varying(20),
        "CommitteeType" character varying(50) NOT NULL,
        "Chamber" character varying(50) NOT NULL,
        "IsActive" boolean NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_Committees" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260508003837_AddBacklogEntities') THEN
    CREATE TABLE "ElectionResults" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "PoliticianId" integer NOT NULL,
        "ElectionYear" integer NOT NULL,
        "Position" character varying(50) NOT NULL,
        "State" character varying(2),
        "City" character varying(100),
        "VotesReceived" bigint NOT NULL,
        "TotalVotes" bigint NOT NULL,
        "VoteShare" numeric(8,4) NOT NULL,
        "IsElected" boolean NOT NULL,
        "ExternalId" character varying(50),
        "CreatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_ElectionResults" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_ElectionResults_Politicians_PoliticianId" FOREIGN KEY ("PoliticianId") REFERENCES "Politicians" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260508003837_AddBacklogEntities') THEN
    CREATE TABLE "PoliticianSalaries" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "PoliticianId" integer NOT NULL,
        "GrossSalary" numeric(15,2) NOT NULL,
        "NetSalary" numeric(15,2) NOT NULL,
        "Allowances" numeric(15,2) NOT NULL,
        "Month" integer NOT NULL,
        "Year" integer NOT NULL,
        "Source" character varying(100),
        "ExternalId" character varying(50),
        "CreatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_PoliticianSalaries" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_PoliticianSalaries_Politicians_PoliticianId" FOREIGN KEY ("PoliticianId") REFERENCES "Politicians" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260508003837_AddBacklogEntities') THEN
    CREATE TABLE "SessionAttendances" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "PoliticianId" integer NOT NULL,
        "SessionDate" timestamp with time zone NOT NULL,
        "IsPresent" boolean NOT NULL,
        "AbsenceReason" character varying(100),
        "AbsenceJustification" character varying(500),
        "Chamber" character varying(50) NOT NULL,
        "ExternalId" character varying(50),
        "CreatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_SessionAttendances" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_SessionAttendances_Politicians_PoliticianId" FOREIGN KEY ("PoliticianId") REFERENCES "Politicians" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260508003837_AddBacklogEntities') THEN
    CREATE TABLE "CommitteeMemberships" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "CommitteeId" integer NOT NULL,
        "PoliticianId" integer NOT NULL,
        "Role" character varying(50) NOT NULL,
        "StartDate" timestamp with time zone,
        "EndDate" timestamp with time zone,
        "CreatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_CommitteeMemberships" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_CommitteeMemberships_Committees_CommitteeId" FOREIGN KEY ("CommitteeId") REFERENCES "Committees" ("Id") ON DELETE CASCADE,
        CONSTRAINT "FK_CommitteeMemberships_Politicians_PoliticianId" FOREIGN KEY ("PoliticianId") REFERENCES "Politicians" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260508003837_AddBacklogEntities') THEN
    CREATE INDEX "IX_AssetDeclarations_ExternalId" ON "AssetDeclarations" ("ExternalId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260508003837_AddBacklogEntities') THEN
    CREATE INDEX "IX_AssetDeclarations_PoliticianId" ON "AssetDeclarations" ("PoliticianId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260508003837_AddBacklogEntities') THEN
    CREATE INDEX "IX_CampaignExpenses_ExternalId" ON "CampaignExpenses" ("ExternalId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260508003837_AddBacklogEntities') THEN
    CREATE INDEX "IX_CampaignExpenses_PoliticianId" ON "CampaignExpenses" ("PoliticianId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260508003837_AddBacklogEntities') THEN
    CREATE INDEX "IX_CommitteeMemberships_CommitteeId_PoliticianId" ON "CommitteeMemberships" ("CommitteeId", "PoliticianId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260508003837_AddBacklogEntities') THEN
    CREATE INDEX "IX_CommitteeMemberships_PoliticianId" ON "CommitteeMemberships" ("PoliticianId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260508003837_AddBacklogEntities') THEN
    CREATE INDEX "IX_Committees_ExternalId" ON "Committees" ("ExternalId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260508003837_AddBacklogEntities') THEN
    CREATE INDEX "IX_ElectionResults_ExternalId" ON "ElectionResults" ("ExternalId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260508003837_AddBacklogEntities') THEN
    CREATE INDEX "IX_ElectionResults_PoliticianId_ElectionYear" ON "ElectionResults" ("PoliticianId", "ElectionYear");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260508003837_AddBacklogEntities') THEN
    CREATE INDEX "IX_PoliticianSalaries_ExternalId" ON "PoliticianSalaries" ("ExternalId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260508003837_AddBacklogEntities') THEN
    CREATE INDEX "IX_PoliticianSalaries_PoliticianId_Year_Month" ON "PoliticianSalaries" ("PoliticianId", "Year", "Month");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260508003837_AddBacklogEntities') THEN
    CREATE INDEX "IX_SessionAttendances_ExternalId" ON "SessionAttendances" ("ExternalId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260508003837_AddBacklogEntities') THEN
    CREATE INDEX "IX_SessionAttendances_PoliticianId_SessionDate" ON "SessionAttendances" ("PoliticianId", "SessionDate");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260508003837_AddBacklogEntities') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260508003837_AddBacklogEntities', '9.0.5');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260517220529_AddVotingAlert') THEN
    CREATE TABLE "VotingAlerts" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "VotingSessionId" integer NOT NULL,
        "AlertLevel" character varying(20) NOT NULL,
        "Score" integer NOT NULL,
        "ScoreBreakdown" character varying(500),
        "DetectedAt" timestamp with time zone NOT NULL,
        "SummaryText" character varying(1000),
        "SignalRSent" boolean NOT NULL,
        "PushSent" boolean NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_VotingAlerts" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_VotingAlerts_VotingSessions_VotingSessionId" FOREIGN KEY ("VotingSessionId") REFERENCES "VotingSessions" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260517220529_AddVotingAlert') THEN
    CREATE INDEX "IX_VotingAlerts_DetectedAt" ON "VotingAlerts" ("DetectedAt");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260517220529_AddVotingAlert') THEN
    CREATE INDEX "IX_VotingAlerts_VotingSessionId" ON "VotingAlerts" ("VotingSessionId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260517220529_AddVotingAlert') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260517220529_AddVotingAlert', '9.0.5');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260520024124_FixSnapshotExternalIdLength') THEN
    ALTER TABLE "Politicians" ALTER COLUMN "ExternalId" TYPE character varying(50);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260520024124_FixSnapshotExternalIdLength') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260520024124_FixSnapshotExternalIdLength', '9.0.5');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260520024557_AddNewPoliticianEntities') THEN
    ALTER TABLE "Politicians" ADD "PartyId" integer;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260520024557_AddNewPoliticianEntities') THEN
    CREATE TABLE "Allowances" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "PoliticianId" integer NOT NULL,
        "AllowanceType" character varying(100) NOT NULL,
        "Amount" numeric(15,2) NOT NULL,
        "Month" integer NOT NULL,
        "Year" integer NOT NULL,
        "Description" character varying(500),
        "Source" character varying(50),
        "ExternalId" character varying(100),
        "CreatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_Allowances" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Allowances_Politicians_PoliticianId" FOREIGN KEY ("PoliticianId") REFERENCES "Politicians" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260520024557_AddNewPoliticianEntities') THEN
    CREATE TABLE "CabinetStaff" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "PoliticianId" integer NOT NULL,
        "FullName" character varying(300) NOT NULL,
        "Role" character varying(100),
        "GrossSalary" numeric(15,2) NOT NULL,
        "NetSalary" numeric(15,2) NOT NULL,
        "StartDate" timestamp with time zone,
        "EndDate" timestamp with time zone,
        "Cpf" character varying(14),
        "ExternalId" character varying(100),
        "Source" character varying(50),
        "Month" integer,
        "Year" integer,
        "CreatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_CabinetStaff" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_CabinetStaff_Politicians_PoliticianId" FOREIGN KEY ("PoliticianId") REFERENCES "Politicians" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260520024557_AddNewPoliticianEntities') THEN
    CREATE TABLE "Parties" (
        "Id" integer GENERATED BY DEFAULT AS IDENTITY,
        "Acronym" character varying(20) NOT NULL,
        "FullName" character varying(200) NOT NULL,
        "Number" integer,
        "FoundedDate" date,
        "President" character varying(200),
        "ExternalId" character varying(100),
        "IsActive" boolean NOT NULL,
        "CreatedAt" timestamp with time zone NOT NULL,
        "UpdatedAt" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_Parties" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260520024557_AddNewPoliticianEntities') THEN
    CREATE INDEX "IX_Politicians_PartyId" ON "Politicians" ("PartyId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260520024557_AddNewPoliticianEntities') THEN
    CREATE INDEX "IX_Allowances_ExternalId" ON "Allowances" ("ExternalId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260520024557_AddNewPoliticianEntities') THEN
    CREATE INDEX "IX_Allowances_PoliticianId_Year_Month_AllowanceType" ON "Allowances" ("PoliticianId", "Year", "Month", "AllowanceType");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260520024557_AddNewPoliticianEntities') THEN
    CREATE INDEX "IX_CabinetStaff_ExternalId" ON "CabinetStaff" ("ExternalId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260520024557_AddNewPoliticianEntities') THEN
    CREATE INDEX "IX_CabinetStaff_PoliticianId_Year_Month" ON "CabinetStaff" ("PoliticianId", "Year", "Month");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260520024557_AddNewPoliticianEntities') THEN
    CREATE UNIQUE INDEX "IX_Parties_Acronym" ON "Parties" ("Acronym");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260520024557_AddNewPoliticianEntities') THEN
    CREATE INDEX "IX_Parties_ExternalId" ON "Parties" ("ExternalId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260520024557_AddNewPoliticianEntities') THEN
    CREATE INDEX "IX_Parties_Number" ON "Parties" ("Number");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260520024557_AddNewPoliticianEntities') THEN
    ALTER TABLE "Politicians" ADD CONSTRAINT "FK_Politicians_Parties_PartyId" FOREIGN KEY ("PartyId") REFERENCES "Parties" ("Id") ON DELETE SET NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260520024557_AddNewPoliticianEntities') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260520024557_AddNewPoliticianEntities', '9.0.5');
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260531024219_MakeCabinetStaffPoliticianIdNullable') THEN
    ALTER TABLE "CabinetStaff" DROP CONSTRAINT "FK_CabinetStaff_Politicians_PoliticianId";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260531024219_MakeCabinetStaffPoliticianIdNullable') THEN
    ALTER TABLE "CabinetStaff" ALTER COLUMN "PoliticianId" DROP NOT NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260531024219_MakeCabinetStaffPoliticianIdNullable') THEN
    ALTER TABLE "CabinetStaff" ADD CONSTRAINT "FK_CabinetStaff_Politicians_PoliticianId" FOREIGN KEY ("PoliticianId") REFERENCES "Politicians" ("Id") ON DELETE SET NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260531024219_MakeCabinetStaffPoliticianIdNullable') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260531024219_MakeCabinetStaffPoliticianIdNullable', '9.0.5');
    END IF;
END $EF$;
COMMIT;

